### ISSUE TITLE
Rails Environment-specific Configuration

### ISSUE THREAD

**Issue by marktran** [lassebunk/human_power#1]
Is there any way to have different configurations for different Rails environments?

``` code
if Rails.env.production?
  disallow :none
else
  disallow :all
end
```

Error:

``` code
NoMethodError (undefined method `env' for HumanPower::Rails:Module):
  config/robots.rb:1:in `block in robots'
  lib/silverpop_middleware.rb:13:in `call'
  lib/health_check_middleware.rb:10:in `call'
```

**Comment by lassebunk** [comment]
Yes, try `::Rails` instead of `Rails`.

I'll look into this.

Thanks.

**Comment by PikachuEXE** [comment]
I guess it's not a bug
Since you are supposed to use `::` if you want top level constant

**Comment by PikachuEXE** [comment]
@lassebunk Close or fix?_?

**Comment by lassebunk** [comment]
This will be fixed. It's unintentional, so it's kind of a bug. :blush:
